### ISSUE TITLE
首頁下方的「觀看範例」連結未設定正確

### ISSUE THREAD

**Issue by unciax** [GSS-FED/vital-ui-kit#13]
首頁下方的「觀看範例」連結未設定正確
連結應設定為 "template.html" ，而非現在的 "#"
![2017-11-12_210753](https://user-images.githubusercontent.com/3615031/32699278-c860e462-c7ed-11e7-86be-14e79fe0f0ca.png)

**Comment by l443018** [comment]
漏...漏掉了 感謝回報
