### ISSUE TITLE
Fix find syntax of deploy script 

### ISSUE THREAD

**Issue by l443018** [GSS-FED/vital-ui-kit#14]
Build failed after #12 syntax modified.
Need to modify "Clean up files from last build" syntax.

<img width="584" alt="screen shot 2017-11-13 at 4 36 35 pm" src="https://user-images.githubusercontent.com/7532024/32716658-c111289e-c891-11e7-8b95-ab3aeb4d9c75.png">

**Comment by cjies** [comment]
I plan to use the native deployment flow that provided by Travis CI. (https://docs.travis-ci.com/user/deployment/)

So we not need to maintain this deploy script anymore.

**Comment by cjies** [comment]
And the `build` branch is still using on production? If not, I suggest remove it, deploy to npm is good enough.

**Comment by l443018** [comment]
Thanks for your suggestion! I'll fix the issue first (because last build I missed some essential sources).
Build branch is no longer need, you can remove it, thanks!

**Comment by l443018** [comment]
Fix this issue by commit: f973d7c43e64001a345a0e9970207b7ef2cdd8f0
