### ISSUE TITLE
IE 不支援 forEach js語法

### ISSUE THREAD

**Issue by JediLiao** [GSS-FED/vital-ui-kit#16]

**Comment by l443018** [comment]
麻煩提供一下是哪個版本的ie，還有error log
感謝～

**Comment by JediLiao** [comment]
我測試過IE9以上都不行
![image](https://user-images.githubusercontent.com/39755712/40701735-adb9648e-6411-11e8-9409-b535a598a0e8.png)

**Comment by 0xycvv** [comment]
我猜是
https://github.com/GSS-FED/vital-ui-kit/blob/781162c69831255d89a4e8de6dae5ca627fae5bc/src/scripts/sg.js#L161-L168
querySelectorAll 出來的是nodelist 不是 js 的 array
