### ISSUE TITLE
Missing less files from kendo

### ISSUE THREAD

**Issue by cjies** [GSS-FED/vital-ui-kit#6]
Unable to compile the LESS files in `src/`,
seems like missing the `kendo-ui-core` dependency.

**Comment by l443018** [comment]
This project we support for kendo-ui-core ver 2014.Q1-2015.Q1,
ver 2015.Q2-2017.R2 will be coming soon!

**Comment by cjies** [comment]
Because git ignored the `bower_components/` folder, so the `kendo-ui-core` that placed in bower_components would not be found. Gulp ran failed in the `uikitStyle` task.

And I remembered that this package is the paid version, so it should not be committed too.
